# +------------------------------------------------------+ 
# |                       FragmentedWatchCore            | 
# +------------------------------------------------------+ 
# This version is experimental!
# This Plugin Is Made by Mainstrike.
# Discord: Mainstrike#2383
# Twitter: CL_Mainstrike
# Or Twitter: CL_MainstrikeMC
# Spigot Name: Mainstrike
# Wiki: https://github.com/Mainstrike/FragmentedWatchCore/wiki/
# ---
# Credit Command Is Not Currently Available in this Version.
Credit: true
